CREATE TABLE `arrivals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saleId` int NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`saleNo` int,
	`saleYear` int,
	`arrivalDate` date,
	`unit` varchar(64),
	`arrivalNo` varchar(128),
	`mark` varchar(128) NOT NULL,
	`sellerName` varchar(256),
	`teaType` enum('Leaf','Dust','Green'),
	`category` varchar(64),
	`invoiceNo` varchar(128),
	`grade` varchar(64),
	`gpNo` varchar(64),
	`gpDate` date,
	`cropYear` int,
	`packages` int,
	`serialFrom` int,
	`serialUpto` int,
	`unitLocation` varchar(32),
	`eachGross` decimal(10,3),
	`eachNet` decimal(10,3),
	`os` int DEFAULT 0,
	`br` int DEFAULT 0,
	`ws` int DEFAULT 0,
	`tr` int DEFAULT 0,
	`nr` int DEFAULT 0,
	`shortage` decimal(10,3) DEFAULT '0',
	`fis` varchar(8),
	`pkgMonth` varchar(32),
	`ewayBillNo` varchar(64),
	`ewayBillDate` date,
	`packageSize` decimal(10,3),
	`packageType` varchar(32),
	`remarks` text,
	`totalNetWeight` decimal(12,3),
	`isNewGarden` boolean DEFAULT false,
	`awrType` enum('ALPHA','NUM','OTHER'),
	`categorizationStatus` enum('pending','auto','manual','confirmed') DEFAULT 'pending',
	`allocationStatus` enum('pending','allocated','excluded') DEFAULT 'pending',
	`saleAllocation` enum('MAIN','SUPPLEMENTARY','EXCLUDED'),
	`salePart` enum('I','II'),
	`sopRuleApplied` varchar(32),
	`uploadBatchId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `arrivals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `auction_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saleId` int NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`lotId` int NOT NULL,
	`lotNo` varchar(32),
	`mark` varchar(128),
	`grade` varchar(64),
	`packages` int,
	`netWeight` decimal(12,3),
	`limitPrice` decimal(10,2),
	`sellingPrice` decimal(10,2),
	`buyerName` varchar(256),
	`buyerCode` varchar(64),
	`soldStatus` enum('SOLD','UNSOLD','WITHDRAWN') NOT NULL,
	`revenue` decimal(14,2),
	`importedAt` timestamp DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auction_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bible_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`centreId` varchar(32),
	`year` int NOT NULL,
	`awrNo` varchar(128),
	`awrDate` date,
	`awrRemarks` text,
	`season` int,
	`category` varchar(64),
	`saleType` varchar(32),
	`provisionalSaleNo` decimal(8,1),
	`sellerName` varchar(256),
	`mark` varchar(128),
	`invoice` varchar(128),
	`gpNo` varchar(64),
	`gpDate` date,
	`grade` varchar(64),
	`packageFrom` int,
	`packageTo` int,
	`pkgs` int,
	`grossWeight` decimal(10,2),
	`netWeight` decimal(10,2),
	`sampleWeight` decimal(8,2),
	`sortWeight` decimal(8,2),
	`totalNetWeight` decimal(12,2),
	`bagType` varchar(16),
	`bagStatus` varchar(16),
	`saleStatus` varchar(64),
	`price` decimal(10,2),
	`saleDate` varchar(32),
	`aucSaleNo` varchar(32),
	`aucLotNo` decimal(10,1),
	`aucPkgs` decimal(10,1),
	`aucInvWt` decimal(12,2),
	`aucPrice` decimal(10,2),
	`aucLastSaleNo` varchar(32),
	`aucValuation` decimal(10,2),
	`buyer1` varchar(256),
	`buyer2` varchar(256),
	`buyer3` varchar(256),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bible_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `buyer_master` (
	`id` int AUTO_INCREMENT NOT NULL,
	`buyerCode` varchar(64),
	`buyerName` varchar(256) NOT NULL,
	`centreId` varchar(32),
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `buyer_master_id` PRIMARY KEY(`id`),
	CONSTRAINT `buyer_master_buyerCode_unique` UNIQUE(`buyerCode`)
);
--> statement-breakpoint
CREATE TABLE `carry_forward_stock` (
	`id` int AUTO_INCREMENT NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`currentSaleId` int NOT NULL,
	`fromSaleId` int,
	`fromSaleLabel` varchar(32),
	`mark` varchar(128) NOT NULL,
	`grade` varchar(64),
	`category` varchar(64),
	`teaType` varchar(32),
	`packages` int,
	`netWeight` decimal(12,3),
	`reason` enum('unsold','withdrawn','partial') DEFAULT 'unsold',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `carry_forward_stock_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `catalogues` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saleId` int NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`catalogueType` enum('kutcha','trade','tasting','limits') NOT NULL,
	`status` enum('draft','ready','published') DEFAULT 'draft',
	`fileUrl` varchar(1024),
	`fileKey` varchar(512),
	`lotCount` int DEFAULT 0,
	`generatedBy` int,
	`generatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `catalogues_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `centre_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`autoCategorizationEnabled` boolean DEFAULT true,
	`newGardenDetectionEnabled` boolean DEFAULT true,
	`duplicateAwrDetectionEnabled` boolean DEFAULT true,
	`minLotSizeCtcLeaf` int DEFAULT 10,
	`minLotSizeCtcDust` int DEFAULT 10,
	`minLotSizeOrthLeaf` int DEFAULT 5,
	`minLotSizeOrthDust` int DEFAULT 5,
	`currentSaleNo` int,
	`currentSaleYear` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `centre_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `centre_settings_centreId_unique` UNIQUE(`centreId`)
);
--> statement-breakpoint
CREATE TABLE `centres` (
	`id` varchar(32) NOT NULL,
	`name` varchar(128) NOT NULL,
	`fullName` varchar(256),
	`region` enum('north','south') NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `centres_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `garden_master` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mark` varchar(128) NOT NULL,
	`sellerName` varchar(256),
	`region` varchar(128),
	`centreId` varchar(32),
	`category` varchar(64),
	`certifications` json,
	`firstSeenSale` varchar(32),
	`lastSeenSale` varchar(32),
	`totalLotsAllTime` int DEFAULT 0,
	`avgPriceAllTime` decimal(10,2),
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `garden_master_id` PRIMARY KEY(`id`),
	CONSTRAINT `garden_master_mark_unique` UNIQUE(`mark`)
);
--> statement-breakpoint
CREATE TABLE `lots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saleId` int NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`lotNo` varchar(32) NOT NULL,
	`arrivalId` int,
	`mark` varchar(128) NOT NULL,
	`sellerName` varchar(256),
	`invoiceNo` varchar(128),
	`grade` varchar(64),
	`category` varchar(64),
	`teaType` varchar(32),
	`packages` int,
	`netWeight` decimal(12,3),
	`invoiceWeight` decimal(12,3),
	`grossWeight` decimal(12,3),
	`sampleQty` decimal(8,3),
	`gpNo` varchar(64),
	`gpDate` date,
	`packageType` varchar(32),
	`packageNo` varchar(64),
	`origin` varchar(128),
	`saleAllocation` enum('MAIN','SUPPLEMENTARY'),
	`salePart` enum('I','II'),
	`gardenRank` int,
	`lotSequence` int,
	`basePrice` decimal(10,2),
	`reservePrice` decimal(10,2),
	`auctioneerValuation` decimal(10,2),
	`musterValue` decimal(10,2),
	`limitPrice` decimal(10,2),
	`lspSp` varchar(32),
	`worth` decimal(10,2),
	`limitsSI` varchar(64),
	`qc` varchar(32),
	`qualityComments` text,
	`tastingRemarks` text,
	`buyerScores` json,
	`soldStatus` enum('PENDING','SOLD','UNSOLD','WITHDRAWN') DEFAULT 'PENDING',
	`sellingPrice` decimal(10,2),
	`buyerName` varchar(256),
	`buyerCode` varchar(64),
	`sampleDrawn` boolean DEFAULT false,
	`stickerGenerated` boolean DEFAULT false,
	`sampleDespatched` boolean DEFAULT false,
	`sampleDespatchDate` date,
	`samplePriority` enum('urgent','high','normal') DEFAULT 'normal',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sales` (
	`id` int AUTO_INCREMENT NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`saleNo` int NOT NULL,
	`saleYear` int NOT NULL,
	`saleLabel` varchar(32),
	`viewType` enum('auctions','private') NOT NULL DEFAULT 'auctions',
	`auctionDate` date,
	`weekNo` int,
	`weekLabel` varchar(32),
	`status` enum('open','locked','post_auction','settled') NOT NULL DEFAULT 'open',
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sales_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sop_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`centreId` varchar(32),
	`ruleNo` int NOT NULL,
	`ruleName` varchar(256) NOT NULL,
	`description` text,
	`conditions` json NOT NULL,
	`allocation` enum('MAIN','SUPPLEMENTARY','EXCLUDED') NOT NULL,
	`salePart` enum('I','II'),
	`priority` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sop_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `upload_batches` (
	`id` varchar(64) NOT NULL,
	`centreId` varchar(32) NOT NULL,
	`saleId` int,
	`fileName` varchar(256),
	`fileUrl` varchar(1024),
	`fileKey` varchar(512),
	`totalRows` int DEFAULT 0,
	`processedRows` int DEFAULT 0,
	`errorRows` int DEFAULT 0,
	`newGardensDetected` int DEFAULT 0,
	`status` enum('uploading','processing','completed','failed') DEFAULT 'uploading',
	`errors` json,
	`uploadedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `upload_batches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('superadmin','admin','manager','taster','viewer') NOT NULL DEFAULT 'viewer';--> statement-breakpoint
ALTER TABLE `users` ADD `centreId` varchar(32);--> statement-breakpoint
ALTER TABLE `users` ADD `region` enum('north','south');--> statement-breakpoint
ALTER TABLE `users` ADD `isActive` boolean DEFAULT true NOT NULL;